// Code generated by "stringer -type=Code"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-0]
	_ = x[ErrNoFound-404]
	_ = x[ErrUserPassword-1109]
	_ = x[ErrCreateSession-1111]
	_ = x[ErrUserLocked-1110]
	_ = x[ErrSession-8001]
	_ = x[ErrDefListSearchNotSupport-8101]
	_ = x[ErrDefListSearchAbnormalField-8102]
	_ = x[ErrDefListSearchTempleNotFound-8103]
	_ = x[ErrDefFirstXNotSupport-8104]
	_ = x[ErrModNotFound-8105]
	_ = x[ErrPatchSettings-8106]
	_ = x[ErrDeleteInnerMod-8107]
	_ = x[ErrCleanRoutes-8108]
	_ = x[ErrCleanMenus-8109]
	_ = x[ErrDelModule-8110]
	_ = x[ErrRouteNotFound-8111]
	_ = x[ErrInnerRouteNotFound-8112]
	_ = x[ErrArgsURLScheme-8113]
	_ = x[ErrArgsRangeType-8114]
	_ = x[ErrArgsRangeCMDTYPE-8115]
	_ = x[ErrArgsRangeNum-8116]
	_ = x[ErrArgsRange-8117]
	_ = x[ErrItemXNotFound-8118]
	_ = x[ErrInnerServer-8119]
	_ = x[ErrAssetValueNoConfig-8120]
	_ = x[ErrCodeNotFound-8121]
	_ = x[ErrLoadSettings-8122]
	_ = x[ErrNoSettingsFound-8123]
	_ = x[ErrParseSettings-8124]
	_ = x[ErrOpenRpcClient-8125]
	_ = x[ErrNoEtcdConfig-8126]
	_ = x[ErrDuplicateKey-8127]
	_ = x[ErrSessionTimeout-8128]
}

const (
	_Code_name_0 = "SUCCESS"
	_Code_name_1 = "ErrNoFound"
	_Code_name_2 = "ErrUserPasswordErrUserLockedErrCreateSession"
	_Code_name_3 = "ErrSession"
	_Code_name_4 = "ErrDefListSearchNotSupportErrDefListSearchAbnormalFieldErrDefListSearchTempleNotFoundErrDefFirstXNotSupportErrModNotFoundErrPatchSettingsErrDeleteInnerModErrCleanRoutesErrCleanMenusErrDelModuleErrRouteNotFoundErrInnerRouteNotFoundErrArgsURLSchemeErrArgsRangeTypeErrArgsRangeCMDTYPEErrArgsRangeNumErrArgsRangeErrItemXNotFoundErrInnerServerErrAssetValueNoConfigErrCodeNotFoundErrLoadSettingsErrNoSettingsFoundErrParseSettingsErrOpenRpcClientErrNoEtcdConfigErrDuplicateKeyErrSessionTimeout"
)

var (
	_Code_index_2 = [...]uint8{0, 15, 28, 44}
	_Code_index_4 = [...]uint16{0, 26, 55, 85, 107, 121, 137, 154, 168, 181, 193, 209, 230, 246, 262, 281, 296, 308, 324, 338, 359, 374, 389, 407, 423, 439, 454, 469, 486}
)

func (i Code) String() string {
	switch {
	case i == 0:
		return _Code_name_0
	case i == 404:
		return _Code_name_1
	case 1109 <= i && i <= 1111:
		i -= 1109
		return _Code_name_2[_Code_index_2[i]:_Code_index_2[i+1]]
	case i == 8001:
		return _Code_name_3
	case 8101 <= i && i <= 8128:
		i -= 8101
		return _Code_name_4[_Code_index_4[i]:_Code_index_4[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
